//Teste de Requisições REST - Posts
@baseURL = http://localhost:4000
@id = 619b7a2987692349f794794f
###
// GET - Lista todos os posts
GET {{baseURL}}/posts
Content-Type: application/json

###
// GET - Lista apenas um post pelo id
GET {{baseURL}}/posts/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo post
POST {{baseURL}}/posts
Content-Type: application/json

{
   "title":"Segundona braba",
   "description": "Aula FATEC",
   "date": "22/11/2021",
   "location": "FATEC-Itu",
   "author": "Carlos Prado"
}


### 
// DELETE - Apaga um post através do id informado
DELETE {{baseURL}}/posts/{{id}}
Content-Type: application/json

###
// PUT - Altera um post pelo ID
PUT {{baseURL}}/posts/
Content-Type: application/json

{
    "_id": "619b68a079d36b09aa85a5fc", 
   "title":"Feriado",
   "description": "Domingao de sol na Paulista",
   "date": "17/05/2020",
   "location": "Av. Paulista, 1732",
   "author": "Victor Hugo"
}


